"""add foreign key to posts

Revision ID: 188dd413fb35
Revises: aae49ae6ff8a
Create Date: 2026-08-20 11:20:19.877827

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "188dd413fb35"
down_revision: str | Sequence[str] | None = "aae49ae6ff8a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "posts", "users", ["user_id"], ["user_id"], ondelete="cascade"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "posts", type_="foreignkey")  # pyright: ignore
    op.drop_column("posts", "user_id")
    # ### end Alembic commands ###
