"""create posts table

Revision ID: 1954353d43b3
Revises:
Create Date: 2026-08-19 14:15:59.433999

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1954353d43b3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
